# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd89b47d2616838cfc9ab67f4aa30254a8d43f644713329395220a1ed62df2fd4bc3e9aecffcd61bc92f0815b61af957bfa8f70dc62bccdb6c46d53ae145b21f

test:
  secret_key_base: 2128620e7399e92e7716f9c482730b6ddb1f798b147ea5d19f66d8569133dbe6e0dd5ed090b640e494b6251f86f4d4f74e2e45bc7b31c44bbb6604cb96fa7c9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
